Repository AY2324S1-CS2103T-W17-2/tp, pull requests merged in 2023-11, with the labels that each got.

#106 Fix find command and edit command
  src/main/java/seedu/letsgethired/logic/commands/EditCommand.java
  src/main/java/seedu/letsgethired/model/ModelManager.java
  src/test/java/seedu/letsgethired/logic/commands/EditCommandTest.java
Labels: bug

#103 Add Multiple Notes
  src/main/java/seedu/letsgethired/logic/Messages.java
  src/main/java/seedu/letsgethired/logic/commands/EditCommand.java
  src/main/java/seedu/letsgethired/logic/commands/FindCommand.java
  src/main/java/seedu/letsgethired/logic/commands/NoteCommand.java
  src/main/java/seedu/letsgethired/logic/commands/NoteDeleteCommand.java
  src/main/java/seedu/letsgethired/logic/commands/NoteInsertCommand.java
  src/main/java/seedu/letsgethired/logic/commands/exceptions/CommandException.java
  src/main/java/seedu/letsgethired/logic/parser/AddCommandParser.java
  src/main/java/seedu/letsgethired/logic/parser/CliSyntax.java
  src/main/java/seedu/letsgethired/logic/parser/DeleteCommandParser.java
  src/main/java/seedu/letsgethired/logic/parser/EditCommandParser.java
  src/main/java/seedu/letsgethired/logic/parser/FindCommandParser.java
  src/main/java/seedu/letsgethired/logic/parser/NoteCommandParser.java
  src/main/java/seedu/letsgethired/logic/parser/ParserUtil.java
  src/main/java/seedu/letsgethired/logic/parser/ViewCommandParser.java
  src/main/java/seedu/letsgethired/model/application/CompanyContainsFieldKeywordsPredicate.java
  src/main/java/seedu/letsgethired/model/application/InternApplication.java
  src/main/java/seedu/letsgethired/model/application/Note.java
  src/main/java/seedu/letsgethired/model/util/SampleDataUtil.java
  src/main/java/seedu/letsgethired/storage/JsonAdaptedInternApplication.java
  src/test/data/JsonSerializableInternTrackerTest/duplicateInternApplicationInternTracker.json
  src/test/data/JsonSerializableInternTrackerTest/invalidInternApplicationInternTracker.json
  src/test/data/JsonSerializableInternTrackerTest/typicalInternApplicationInternTracker.json
  src/test/java/seedu/letsgethired/logic/commands/CommandTestUtil.java
  src/test/java/seedu/letsgethired/logic/commands/NoteDeleteCommandTest.java
  src/test/java/seedu/letsgethired/logic/commands/NoteInsertCommandTest.java
  src/test/java/seedu/letsgethired/logic/parser/FindCommandParserTest.java
  src/test/java/seedu/letsgethired/logic/parser/InternTrackerParserTest.java
  src/test/java/seedu/letsgethired/logic/parser/NoteCommandParserTest.java
  src/test/java/seedu/letsgethired/logic/parser/ParserUtilTest.java
  src/test/java/seedu/letsgethired/model/application/CompanyContainsFieldKeywordsPredicateTest.java
  src/test/java/seedu/letsgethired/model/application/InternApplicationTest.java
  src/test/java/seedu/letsgethired/model/application/NoteTest.java
  src/test/java/seedu/letsgethired/storage/JsonAdaptedInternApplicationTest.java
  src/test/java/seedu/letsgethired/testutil/InternApplicationBuilder.java
  src/test/java/seedu/letsgethired/testutil/InternApplicationUtil.java
Labels: enhancement

#105 UI Tweaks and Bug Fixes
  src/main/java/seedu/letsgethired/logic/Messages.java
  src/main/java/seedu/letsgethired/logic/commands/AddCommand.java
  src/main/java/seedu/letsgethired/logic/commands/CommandResult.java
  src/main/java/seedu/letsgethired/logic/commands/EditCommand.java
  src/main/java/seedu/letsgethired/logic/commands/NoteDeleteCommand.java
  src/main/java/seedu/letsgethired/logic/commands/NoteInsertCommand.java
  src/main/java/seedu/letsgethired/logic/commands/ViewCommand.java
  src/main/java/seedu/letsgethired/model/application/CompanyContainsFieldKeywordsPredicate.java
  src/main/java/seedu/letsgethired/model/application/InternApplication.java
  src/main/java/seedu/letsgethired/model/application/Status.java
  src/main/java/seedu/letsgethired/storage/JsonAdaptedInternApplication.java
  src/main/java/seedu/letsgethired/ui/InternApplicationCard.java
  src/main/java/seedu/letsgethired/ui/InternApplicationListPanel.java
  src/main/java/seedu/letsgethired/ui/MainWindow.java
  src/main/java/seedu/letsgethired/ui/SelectView.java
  src/main/java/seedu/letsgethired/ui/UiManager.java
  src/main/resources/view/HelpWindow.css
  src/main/resources/view/InternApplicationListCard.fxml
  src/main/resources/view/InternApplicationListPanel.fxml
  src/main/resources/view/LightTheme.css
  src/main/resources/view/MainWindow.fxml
  src/main/resources/view/SelectView.fxml
  src/test/java/seedu/letsgethired/logic/commands/AddCommandIntegrationTest.java
  src/test/java/seedu/letsgethired/logic/commands/AddCommandTest.java
  src/test/java/seedu/letsgethired/logic/commands/CommandResultTest.java
  src/test/java/seedu/letsgethired/logic/commands/CommandTestUtil.java
  src/test/java/seedu/letsgethired/logic/commands/EditCommandTest.java
  src/test/java/seedu/letsgethired/logic/commands/NoteDeleteCommandTest.java
  src/test/java/seedu/letsgethired/logic/commands/NoteInsertCommandTest.java
  src/test/java/seedu/letsgethired/logic/commands/ViewCommandTest.java
  src/test/java/seedu/letsgethired/model/application/InternApplicationTest.java
  src/test/java/seedu/letsgethired/model/application/UniqueInternApplicationListTest.java
  src/test/java/seedu/letsgethired/storage/JsonAdaptedInternApplicationTest.java
  src/test/java/seedu/letsgethired/testutil/InternApplicationBuilder.java
Labels: bug, enhancement

#112 Add sort for deadline
  src/main/java/seedu/letsgethired/logic/parser/SortCommandParser.java
  src/main/java/seedu/letsgethired/model/application/Company.java
  src/main/java/seedu/letsgethired/model/application/Cycle.java
  src/main/java/seedu/letsgethired/model/application/Deadline.java
  src/main/java/seedu/letsgethired/model/application/InternApplicationComparator.java
  src/main/java/seedu/letsgethired/model/application/Role.java
  src/main/java/seedu/letsgethired/model/application/Status.java
  src/test/java/seedu/letsgethired/logic/commands/CommandTestUtil.java
  src/test/java/seedu/letsgethired/logic/parser/SortCommandParserTest.java
  src/test/java/seedu/letsgethired/model/application/CompanyTest.java
  src/test/java/seedu/letsgethired/model/application/CycleTest.java
  src/test/java/seedu/letsgethired/model/application/RoleTest.java
  src/test/java/seedu/letsgethired/model/application/StatusTest.java
Labels: enhancement, priority.MEDIUM

#111 Add some assertions for methods associated with undo and view.
  src/main/java/seedu/letsgethired/logic/commands/ViewCommand.java
  src/main/java/seedu/letsgethired/model/VersionedInternTracker.java
Labels: enhancement

#108 Improve testing issue93
  src/main/java/seedu/letsgethired/model/InternTracker.java
  src/main/java/seedu/letsgethired/model/application/Deadline.java
  src/test/data/JsonSerializableInternTrackerTest/typicalInternApplicationInternTracker.json
  src/test/java/seedu/letsgethired/logic/LogicManagerTest.java
  src/test/java/seedu/letsgethired/logic/commands/ClearCommandTest.java
  src/test/java/seedu/letsgethired/logic/commands/CommandTestUtil.java
  src/test/java/seedu/letsgethired/logic/commands/SortCommandTest.java
  src/test/java/seedu/letsgethired/logic/parser/InternTrackerParserTest.java
  src/test/java/seedu/letsgethired/logic/parser/SortCommandParserTest.java
  src/test/java/seedu/letsgethired/model/InternTrackerTest.java
  src/test/java/seedu/letsgethired/model/application/CompanyContainsFieldKeywordsPredicateTest.java
  src/test/java/seedu/letsgethired/model/application/DeadlineTest.java
  src/test/java/seedu/letsgethired/model/application/InternApplicationComparatorTest.java
  src/test/java/seedu/letsgethired/model/application/InternApplicationTest.java
  src/test/java/seedu/letsgethired/model/application/UniqueInternApplicationListTest.java
  src/test/java/seedu/letsgethired/storage/JsonAdaptedInternApplicationTest.java
  src/test/java/seedu/letsgethired/storage/StorageManagerTest.java
  src/test/java/seedu/letsgethired/testutil/InternApplicationBuilder.java
  src/test/java/seedu/letsgethired/testutil/TypicalInternApplications.java
Labels: enhancement

#113 Add downloadJar.png
  docs/images/SeEduLogo.png
  docs/images/tutorial/downloadJar.png
  docs/index.md
Labels: bug, documentation

#117 Remove Google Inc from Sample Data
  src/main/java/seedu/letsgethired/model/util/SampleDataUtil.java
Labels: bug

#118 Fix UI resizing bug
  src/main/resources/view/InternApplicationListPanel.fxml
  src/main/resources/view/MainWindow.fxml
Labels: bug

#160 Fix find bugs
  src/main/java/seedu/letsgethired/logic/parser/FindCommandParser.java
  src/main/java/seedu/letsgethired/model/application/CompanyContainsFieldKeywordsPredicate.java
  src/main/java/seedu/letsgethired/model/application/Note.java
Labels: bug

#164 Fix Note Bugs
  src/main/java/seedu/letsgethired/logic/Messages.java
  src/main/java/seedu/letsgethired/logic/commands/NoteCommand.java
  src/main/java/seedu/letsgethired/logic/commands/NoteDeleteCommand.java
  src/main/java/seedu/letsgethired/logic/parser/NoteCommandParser.java
  src/main/java/seedu/letsgethired/logic/parser/ParserUtil.java
  src/main/java/seedu/letsgethired/model/application/Note.java
  src/test/java/seedu/letsgethired/logic/commands/NoteDeleteCommandTest.java
  src/test/java/seedu/letsgethired/logic/parser/ParserUtilTest.java
Labels: bug

#169 Fix bugs
  docs/UserGuide.md
  src/main/java/seedu/letsgethired/logic/parser/AddCommandParser.java
  src/main/java/seedu/letsgethired/logic/parser/FindCommandParser.java
  src/main/java/seedu/letsgethired/logic/parser/SortCommandParser.java
  src/main/java/seedu/letsgethired/model/application/Company.java
  src/main/java/seedu/letsgethired/model/application/Cycle.java
  src/main/java/seedu/letsgethired/model/application/Role.java
  src/test/data/JsonInternTrackerStorageTest/invalidInternApplicationInternTracker.json
  src/test/java/seedu/letsgethired/logic/LogicManagerTest.java
  src/test/java/seedu/letsgethired/logic/commands/CommandTestUtil.java
  src/test/java/seedu/letsgethired/logic/parser/AddCommandParserTest.java
  src/test/java/seedu/letsgethired/logic/parser/ParserUtilTest.java
  src/test/java/seedu/letsgethired/model/application/CompanyTest.java
  src/test/java/seedu/letsgethired/model/application/InternApplicationTest.java
  src/test/java/seedu/letsgethired/storage/JsonAdaptedInternApplicationTest.java
Labels: bug

#174 UI Bug Fixes
  src/main/java/seedu/letsgethired/ui/InternApplicationListCard.java
  src/main/java/seedu/letsgethired/ui/InternApplicationListPanel.java
  src/main/java/seedu/letsgethired/ui/MainWindow.java
Labels: bug

#170 Update Note Command DG for multiple notes
  docs/DeveloperGuide.md
  docs/diagrams/HousekeepSequenceDiagram.puml
  docs/diagrams/NoteCommandClassDiagram.puml
  docs/diagrams/NoteDeleteCommandSequenceDiagram.puml
  docs/diagrams/NoteInsertCommandSequenceDiagram.puml
Labels: documentation

#175 Fix sort order incorrectly taking in multiple prefixes
  src/main/java/seedu/letsgethired/logic/Messages.java
  src/main/java/seedu/letsgethired/logic/parser/ArgumentMultimap.java
  src/main/java/seedu/letsgethired/logic/parser/SortCommandParser.java
  src/test/java/seedu/letsgethired/logic/commands/CommandTestUtil.java
  src/test/java/seedu/letsgethired/logic/parser/SortCommandParserTest.java
Labels: bug

#181 Update PPP (Aprup Kale)
  docs/AboutUs.md
  docs/team/aprupkale.md
Labels: documentation

#188 Add Draft for PPP
  docs/team/tim-pipi.md
Labels: documentation

#178 Fix invalid date for deadline
  src/main/java/seedu/letsgethired/logic/parser/AddCommandParser.java
  src/main/java/seedu/letsgethired/model/application/Deadline.java
  src/test/java/seedu/letsgethired/logic/parser/ParserUtilTest.java
  src/test/java/seedu/letsgethired/model/application/DeadlineTest.java
Labels: bug

#176 Fix Cycle Bug
  src/main/java/seedu/letsgethired/model/application/Cycle.java
Labels: bug

#200 Update AboutUs - Timothy
  docs/AboutUs.md
Labels: documentation

#197 Add appendix for effort, highlighting the key features of our applica…
  docs/DeveloperGuide.md
  docs/_markbind/layouts/default.md
Labels: documentation

#203 Update PPP
  docs/team/tim-pipi.md
Labels: documentation

#204 Update headers to use TitleCase
  docs/Configuration.md
  docs/DevOps.md
  docs/DeveloperGuide.md
  docs/Documentation.md
  docs/Logging.md
  docs/SettingUp.md
  docs/Testing.md
  docs/_markbind/layouts/default.md
Labels: documentation

#202 Planned enhancements
  docs/AboutUs.md
  docs/DeveloperGuide.md
  docs/_markbind/layouts/default.md
Labels: documentation

#209 Planned Enhancements - Redo
  docs/DeveloperGuide.md
Labels: documentation

#208 Planned Enhancement - Sort by Multiple Fields
  docs/DeveloperGuide.md
  docs/UserGuide.md
  docs/team/aprupkale.md
  docs/team/tim-pipi.md
  docs/team/zhengyup.md
  docs/team/zsh-eng.md
Labels: documentation

#212 Fix sort command bug
  src/main/java/seedu/letsgethired/model/application/Company.java
Labels: bug

#215 Appendix: Add Default Sort, Note Edit and Sort Status Enhancement into the DG
  docs/DeveloperGuide.md
Labels: documentation

#199 UG Links
  docs/UserGuide.md
Labels: documentation

#207 Fix DG
  docs/DeveloperGuide.md
  docs/Testing.md
  docs/UserGuide.md
  docs/diagrams/AddSequenceDiagram.puml
  docs/diagrams/ArchitectureSequenceDiagram.puml
  docs/diagrams/CommitActivityDiagram.puml
  docs/diagrams/DeleteSequenceDiagram.puml
  docs/diagrams/FindCommandSequenceDiagram.puml
  docs/diagrams/NoteDeleteCommandSequenceDiagram.puml
  docs/diagrams/NoteInsertCommandSequenceDiagram.puml
  docs/diagrams/SelectViewSequenceDiagram.puml
  docs/diagrams/SortSequenceDiagram.puml
  docs/diagrams/UndoSequenceDiagram.puml
Labels: documentation

#213 Add Appendix: Instructions for Manual Testing
  docs/DeveloperGuide.md
  docs/team/aprupkale.md
Labels: documentation

#220 Update downloadJar image and Fix Formatting Error
  docs/UserGuide.md
  docs/images/Annotated Images.pptx
  docs/images/tutorial/downloadJar.png
Labels: documentation

#222 Fix UG errors
  docs/UserGuide.md
Labels: documentation

#180 Update PPP (You Wei)
  docs/team/tyouwei.md
Labels: documentation

#223 Fix typo errors in You Wei PPP
  docs/team/tyouwei.md
Labels: bug, documentation
