Repository AY2324S1-CS2103T-W17-2/tp, pull requests merged in 2023-10, with the labels that each got.

#16 Update AboutUs and add docs/images/aprupkale.png
  .github/workflows/docs.yml
  docs/AboutUs.md
  docs/_markbind/layouts/default.md
  docs/images/aprupkale.png
  docs/site.json
  docs/team/aprupkale.md
Labels: documentation

#17 Add AboutUs for Zhi Sheng
  docs/AboutUs.md
  docs/images/zsh-eng.jpg
  docs/team/zsh_eng.md
Labels: documentation

#22 Update AboutUs
  docs/AboutUs.md
  docs/images/johndoe.png
  docs/images/tyouwei.png
  docs/team/johndoe.md
  docs/team/tyouwei.md
Labels: documentation

#20 Update About-Us zhengyup
  docs/AboutUs.md
  docs/images/zhengyup.png
  docs/team/zhengyup.md
Labels: documentation

#28 Add NFR and Glossary to DG
  docs/AboutUs.md
  docs/DeveloperGuide.md
  docs/team/zsh-eng.md
Labels: documentation

#33 Update ReadMe - Branch Issue 19
  README.md
  docs/_markbind/layouts/default.md
  docs/images/Ui.png
Labels: documentation

#39 Add Link to developer guide to README
  README.md
Labels: documentation

#43 edit use cases after the tutorial
  docs/DeveloperGuide.md
Labels: documentation

#45 Rename "Phone" to "Role"
  src/main/java/seedu/address/logic/Messages.java
  src/main/java/seedu/address/logic/commands/AddCommand.java
  src/main/java/seedu/address/logic/commands/EditCommand.java
  src/main/java/seedu/address/logic/parser/AddCommandParser.java
  src/main/java/seedu/address/logic/parser/CliSyntax.java
  src/main/java/seedu/address/logic/parser/EditCommandParser.java
  src/main/java/seedu/address/logic/parser/ParserUtil.java
  src/main/java/seedu/address/model/application/InternApplication.java
  src/main/java/seedu/address/model/application/Phone.java
  src/main/java/seedu/address/model/application/Role.java
  src/main/java/seedu/address/model/util/SampleDataUtil.java
  src/main/java/seedu/address/storage/JsonAdaptedInternApplication.java
  src/main/java/seedu/address/ui/PersonCard.java
  src/main/resources/view/PersonListCard.fxml
  src/test/data/JsonAddressBookStorageTest/invalidAndValidPersonAddressBook.json
  src/test/data/JsonAddressBookStorageTest/invalidPersonAddressBook.json
  src/test/data/JsonSerializableAddressBookTest/duplicatePersonAddressBook.json
  src/test/data/JsonSerializableAddressBookTest/invalidPersonAddressBook.json
  src/test/data/JsonSerializableAddressBookTest/typicalPersonsAddressBook.json
  src/test/java/seedu/address/logic/LogicManagerTest.java
  src/test/java/seedu/address/logic/commands/CommandTestUtil.java
  src/test/java/seedu/address/logic/commands/EditCommandTest.java
  src/test/java/seedu/address/logic/commands/EditInternApplicationDescriptorTest.java
  src/test/java/seedu/address/logic/parser/AddCommandParserTest.java
  src/test/java/seedu/address/logic/parser/EditCommandParserTest.java
  src/test/java/seedu/address/logic/parser/ParserUtilTest.java
  src/test/java/seedu/address/model/application/InternApplicationTest.java
  src/test/java/seedu/address/model/application/NameContainsKeywordsPredicateTest.java
  src/test/java/seedu/address/model/application/PhoneTest.java
  src/test/java/seedu/address/model/application/RoleTest.java
  src/test/java/seedu/address/storage/JsonAdaptedInternApplicationTest.java
  src/test/java/seedu/address/testutil/EditPersonDescriptorBuilder.java
  src/test/java/seedu/address/testutil/InternApplicationBuilder.java
  src/test/java/seedu/address/testutil/PersonUtil.java
  src/test/java/seedu/address/testutil/TypicalInternApplications.java
Labels: enhancement

#46 Update "Email" in Model to "Cycle"
  docs/diagrams/BetterModelClassDiagram.puml
  docs/diagrams/ModelClassDiagram.puml
  docs/tutorials/AddRemark.md
  docs/tutorials/RemovingFields.md
  src/main/java/seedu/address/logic/Messages.java
  src/main/java/seedu/address/logic/commands/AddCommand.java
  src/main/java/seedu/address/logic/commands/EditCommand.java
  src/main/java/seedu/address/logic/parser/AddCommandParser.java
  src/main/java/seedu/address/logic/parser/CliSyntax.java
  src/main/java/seedu/address/logic/parser/EditCommandParser.java
  src/main/java/seedu/address/logic/parser/ParserUtil.java
  src/main/java/seedu/address/model/application/Cycle.java
  src/main/java/seedu/address/model/application/Email.java
  src/main/java/seedu/address/model/application/InternApplication.java
  src/main/java/seedu/address/model/util/SampleDataUtil.java
  src/main/java/seedu/address/storage/JsonAdaptedInternApplication.java
  src/main/java/seedu/address/ui/PersonCard.java
  src/main/resources/view/PersonListCard.fxml
  src/test/data/JsonAddressBookStorageTest/invalidAndValidPersonAddressBook.json
  src/test/data/JsonAddressBookStorageTest/invalidPersonAddressBook.json
  src/test/data/JsonSerializableAddressBookTest/duplicatePersonAddressBook.json
  src/test/data/JsonSerializableAddressBookTest/invalidPersonAddressBook.json
  src/test/data/JsonSerializableAddressBookTest/typicalPersonsAddressBook.json
  src/test/java/seedu/address/logic/LogicManagerTest.java
  src/test/java/seedu/address/logic/commands/CommandTestUtil.java
  src/test/java/seedu/address/logic/commands/EditInternApplicationDescriptorTest.java
  src/test/java/seedu/address/logic/parser/AddCommandParserTest.java
  src/test/java/seedu/address/logic/parser/EditCommandParserTest.java
  src/test/java/seedu/address/logic/parser/ParserUtilTest.java
  src/test/java/seedu/address/model/application/CycleTest.java
  src/test/java/seedu/address/model/application/EmailTest.java
  src/test/java/seedu/address/model/application/InternApplicationTest.java
  src/test/java/seedu/address/model/application/NameContainsKeywordsPredicateTest.java
  src/test/java/seedu/address/storage/JsonAdaptedInternApplicationTest.java
  src/test/java/seedu/address/testutil/EditPersonDescriptorBuilder.java
  src/test/java/seedu/address/testutil/InternApplicationBuilder.java
  src/test/java/seedu/address/testutil/PersonUtil.java
  src/test/java/seedu/address/testutil/TypicalInternApplications.java
Labels: enhancement

#56 Better find command
  docs/UserGuide.md
  src/main/java/seedu/letsgethired/logic/commands/FindCommand.java
  src/main/java/seedu/letsgethired/logic/parser/FindCommandParser.java
  src/main/java/seedu/letsgethired/model/application/CompanyPartialMatchPredicate.java
  src/test/java/seedu/letsgethired/logic/commands/CommandTestUtil.java
  src/test/java/seedu/letsgethired/logic/commands/FindCommandTest.java
  src/test/java/seedu/letsgethired/logic/parser/FindCommandParserTest.java
  src/test/java/seedu/letsgethired/logic/parser/InternTrackerParserTest.java
  src/test/java/seedu/letsgethired/model/ModelManagerTest.java
  src/test/java/seedu/letsgethired/model/application/CompanyPartialMatchPredicateTest.java
Labels: enhancement, type.Story, priority.MEDIUM

#57 Add Note Command
  docs/UserGuide.md
  src/main/java/seedu/letsgethired/logic/commands/EditCommand.java
  src/main/java/seedu/letsgethired/logic/commands/NoteCommand.java
  src/main/java/seedu/letsgethired/logic/parser/AddCommandParser.java
  src/main/java/seedu/letsgethired/logic/parser/CliSyntax.java
  src/main/java/seedu/letsgethired/logic/parser/InternTrackerParser.java
  src/main/java/seedu/letsgethired/logic/parser/NoteCommandParser.java
  src/main/java/seedu/letsgethired/logic/parser/ParserUtil.java
  src/main/java/seedu/letsgethired/model/application/InternApplication.java
  src/main/java/seedu/letsgethired/model/application/Note.java
  src/main/java/seedu/letsgethired/model/util/SampleDataUtil.java
  src/main/java/seedu/letsgethired/storage/JsonAdaptedInternApplication.java
  src/main/java/seedu/letsgethired/ui/InternApplicationCard.java
  src/main/resources/view/InternApplicationListCard.fxml
  src/test/data/JsonInternTrackerStorageTest/invalidAndValidInternApplicationInternTracker.json
  src/test/data/JsonInternTrackerStorageTest/invalidInternApplicationInternTracker.json
  src/test/data/JsonSerializableInternTrackerTest/duplicateInternApplicationInternTracker.json
  src/test/data/JsonSerializableInternTrackerTest/invalidInternApplicationInternTracker.json
  src/test/data/JsonSerializableInternTrackerTest/typicalInternApplicationInternTracker.json
  src/test/java/seedu/letsgethired/logic/LogicManagerTest.java
  src/test/java/seedu/letsgethired/logic/commands/CommandTestUtil.java
  src/test/java/seedu/letsgethired/logic/commands/NoteCommandTest.java
  src/test/java/seedu/letsgethired/logic/parser/AddCommandParserTest.java
  src/test/java/seedu/letsgethired/logic/parser/InternTrackerParserTest.java
  src/test/java/seedu/letsgethired/logic/parser/NoteCommandParserTest.java
  src/test/java/seedu/letsgethired/model/application/InternApplicationTest.java
  src/test/java/seedu/letsgethired/model/application/NoteTest.java
  src/test/java/seedu/letsgethired/storage/JsonAdaptedInternApplicationTest.java
  src/test/java/seedu/letsgethired/testutil/InternApplicationBuilder.java
  src/test/java/seedu/letsgethired/testutil/InternApplicationUtil.java
  src/test/java/seedu/letsgethired/testutil/TypicalInternApplications.java
Labels: type.Story, priority.HIGH

#59 Fix issues with note
  src/main/java/seedu/letsgethired/logic/Messages.java
  src/main/java/seedu/letsgethired/logic/commands/NoteCommand.java
  src/main/java/seedu/letsgethired/logic/parser/NoteCommandParser.java
  src/main/java/seedu/letsgethired/model/application/Note.java
  src/test/java/seedu/letsgethired/logic/commands/NoteCommandTest.java
  src/test/java/seedu/letsgethired/logic/parser/NoteCommandParserTest.java
  src/test/java/seedu/letsgethired/model/application/NoteTest.java
  src/test/java/seedu/letsgethired/storage/JsonAdaptedInternApplicationTest.java
Labels: bug, type.Story, priority.HIGH

#58 GUI Improvements
  src/main/java/seedu/letsgethired/logic/Messages.java
  src/main/java/seedu/letsgethired/logic/commands/AddCommand.java
  src/main/java/seedu/letsgethired/logic/commands/CommandResult.java
  src/main/java/seedu/letsgethired/logic/commands/DeleteCommand.java
  src/main/java/seedu/letsgethired/logic/commands/EditCommand.java
  src/main/java/seedu/letsgethired/logic/commands/NoteCommand.java
  src/main/java/seedu/letsgethired/logic/commands/ViewCommand.java
  src/main/java/seedu/letsgethired/model/application/InternApplication.java
  src/main/java/seedu/letsgethired/model/application/Note.java
  src/main/java/seedu/letsgethired/model/application/Role.java
  src/main/java/seedu/letsgethired/ui/CommandExecutor.java
  src/main/java/seedu/letsgethired/ui/InternApplicationCard.java
  src/main/java/seedu/letsgethired/ui/InternApplicationListPanel.java
  src/main/java/seedu/letsgethired/ui/InternApplicationUtilityButton.java
  src/main/java/seedu/letsgethired/ui/MainWindow.java
  src/main/java/seedu/letsgethired/ui/SelectView.java
  src/main/resources/view/DarkTheme.css
  src/main/resources/view/InternApplicationListCard.fxml
  src/main/resources/view/InternApplicationUtilityButton.fxml
  src/main/resources/view/MainWindow.fxml
  src/main/resources/view/SelectView.fxml
  src/test/java/seedu/letsgethired/logic/commands/AddCommandIntegrationTest.java
  src/test/java/seedu/letsgethired/logic/commands/AddCommandTest.java
  src/test/java/seedu/letsgethired/logic/commands/CommandResultTest.java
  src/test/java/seedu/letsgethired/logic/commands/CommandTestUtil.java
  src/test/java/seedu/letsgethired/logic/commands/DeleteCommandTest.java
  src/test/java/seedu/letsgethired/logic/commands/EditCommandTest.java
  src/test/java/seedu/letsgethired/logic/commands/ExitCommandTest.java
  src/test/java/seedu/letsgethired/logic/commands/HelpCommandTest.java
  src/test/java/seedu/letsgethired/logic/commands/NoteCommandTest.java
  src/test/java/seedu/letsgethired/logic/commands/ViewCommandTest.java
  src/test/java/seedu/letsgethired/model/InternTrackerTest.java
  src/test/java/seedu/letsgethired/model/UserPrefsTest.java
  src/test/java/seedu/letsgethired/model/application/InternApplicationTest.java
Labels: enhancement, priority.HIGH

#72 Fix help and exit command
  src/main/java/seedu/letsgethired/logic/commands/CommandResult.java
Labels: bug

#74 Set wrapText to true
  src/main/java/seedu/letsgethired/ui/ResultDisplay.java
  src/main/java/seedu/letsgethired/ui/SelectView.java
Labels: bug, enhancement

#78 Fix feedback to user for Edit and Note commands
  src/main/java/seedu/letsgethired/logic/commands/EditCommand.java
  src/main/java/seedu/letsgethired/logic/commands/NoteCommand.java
  src/test/java/seedu/letsgethired/logic/commands/NoteCommandTest.java
Labels: bug

#86 Update user guide
  docs/UserGuide.md
  docs/images/Ui.jpg
  docs/images/Ui.png
  docs/images/addExample1.jpg
  docs/images/addExample2.jpg
  docs/images/deleteExample.jpg
  docs/images/downloadJar.jpg
  docs/images/editExample.jpg
  docs/images/findExample.jpg
  docs/images/helpExample.jpg
  docs/images/listExample.jpg
  docs/images/noteExample.jpg
  docs/images/viewExample.jpg
Labels: documentation

#81 Add Enums for Status Input Validation
  build.gradle
  src/main/java/seedu/letsgethired/model/application/Status.java
  src/main/java/seedu/letsgethired/ui/InternApplicationCard.java
  src/main/java/seedu/letsgethired/ui/InternApplicationUtilityButton.java
  src/test/java/seedu/letsgethired/model/application/StatusTest.java
  src/test/java/seedu/letsgethired/storage/JsonInternTrackerStorageTest.java
  src/test/java/seedu/letsgethired/testutil/TypicalInternApplications.java
Labels: bug, enhancement

#87 Add markdown documentation for DG
  docs/DeveloperGuide.md
  docs/diagrams/HousekeepSequenceDiagram.puml
  docs/diagrams/SelectViewSequenceDiagram.puml
Labels: documentation

#73 Add proposed implementation for sort
  docs/DeveloperGuide.md
  docs/diagrams/SortSequenceDiagram.puml
Labels: documentation

#88 Update Documentation
  docs/UserGuide.md
  docs/index.md
Labels: documentation

#95 Update Developer Guide - Add implementation for Note and Find Commands
  README.md
  docs/DeveloperGuide.md
  docs/diagrams/FindCommandSequenceDiagram.puml
  docs/diagrams/NoteCommandSequenceDiagram.puml
Labels: documentation

#89 Add Sort Command
  src/main/java/seedu/letsgethired/Main.java
  src/main/java/seedu/letsgethired/logic/commands/SortCommand.java
  src/main/java/seedu/letsgethired/logic/parser/InternTrackerParser.java
  src/main/java/seedu/letsgethired/logic/parser/ParserUtil.java
  src/main/java/seedu/letsgethired/logic/parser/SortCommandParser.java
  src/main/java/seedu/letsgethired/logic/parser/SortOrder.java
  src/main/java/seedu/letsgethired/model/Model.java
  src/main/java/seedu/letsgethired/model/ModelManager.java
  src/main/java/seedu/letsgethired/model/application/InternApplicationComparator.java
  src/test/java/seedu/letsgethired/logic/commands/AddCommandTest.java
  src/test/java/seedu/letsgethired/logic/commands/CommandTestUtil.java
  src/test/java/seedu/letsgethired/logic/commands/SortCommandTest.java
  src/test/java/seedu/letsgethired/logic/parser/SortCommandParserTest.java
  src/test/java/seedu/letsgethired/model/ModelManagerTest.java
  src/test/java/seedu/letsgethired/model/application/InternApplicationComparatorTest.java
Labels: enhancement, type.Story, priority.MEDIUM

#101 UI update
  src/main/java/seedu/letsgethired/logic/Messages.java
  src/main/java/seedu/letsgethired/model/application/Status.java
  src/main/java/seedu/letsgethired/ui/InternApplicationCard.java
  src/main/java/seedu/letsgethired/ui/MainWindow.java
  src/main/java/seedu/letsgethired/ui/UiManager.java
  src/main/resources/view/InternApplicationListCard.fxml
  src/main/resources/view/InternApplicationListPanel.fxml
  src/main/resources/view/InternApplicationUtilityButton.fxml
  src/main/resources/view/LightTheme.css
  src/main/resources/view/MainWindow.fxml
  src/main/resources/view/StatusBarFooter.fxml
  src/test/java/seedu/letsgethired/model/application/StatusTest.java
Labels: enhancement, priority.MEDIUM

#99 Update Developer Guide
  docs/DeveloperGuide.md
  docs/diagrams/AddSequenceDiagram.puml
  docs/index.md
Labels: documentation
